# Spring application property
server:
  port: 80


# Neural network configuration
perceptron:
  learningRate: 0.1

  layers:
    - name: Input
      size: 784
    - name: Hidden 1
      size: 112
    - name: Output
      size: 10
